FROM node:20-alpine

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm@9.1.2

# Copy dependency files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install


EXPOSE 3000

CMD ["pnpm", "dev"] 